# Copyright (c) 2024, JcxAu
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# See the LICENSE file for more details.
SimplifiedChinese_English = {
    '暂无': 'None',
    '开启': 'Open',
    '关闭': 'Close',
    '选择': 'Select',
    '是否启用SSL证书验证 ?\n': 'Do you want to enable SSL certificate verification?\n',
    '现在的状态为: ': 'The current status is: ',
    '唔...要不还是都爬吧': 'Hmm...How about using both download methods',
    '   请设置下载模式 !   ': '     Please set the download mode!     ',
    '下...下载负数张图片!?': 'Download negative number of images?!',
    '   不能填负数哦 !   ': '   Cannot fill in negative numbers!   ',
    '你是认真的吗 ?': 'Are you serious?',
    '  请输入数字 !  ': '   Please enter a number!   ',
    '请输入下载的数量': 'Please enter the number of downloads',
    '目前设置的下载数量为: ': 'The current number of downloads set is: ',
    '确定': 'Confirm',
    '欸嘿, 还是我技高一筹 !': 'Hey hey, I am still better at it!',
    '只能打开一个窗口哦 !': '   Only one window can be opened!   ',
    '关于': 'About',
    '请选择下载的模式': 'Please select the download mode',
    '通过图片所在的网页获取': 'Obtaining through the webpage where the images are located',
    '通过图片自身的网址获取': 'Obtaining them through the website of the images themselves',
    '目前的下载设置为: ': 'The current download setting is: \n',
    '惊不惊喜, 意不意外 ?': 'Feel surprised? Feel off-guard?',
    '帮助': 'Help',
    '请先进行下载数量, 下载模式的设置。\n如果出错了, 可以先切换下载模式, 再尝试。\n注意:\n设置语言选项会使程序退出, 再启动程序, 更改便会生效。': 'Please set the download quantity and download mode first.\nIf there are still errors,\nyou can switch to download mode first and then try again.\nAttention:\nSetting language options will cause the program to exit,\nand restarting the program will take effect.',
    '下载报告': 'Download Report',
    '成功: ': 'Success: ',
    '失败: ': 'Fail: ',
    '嗯? 没有下载吗 ?': 'Hmm? Has the images not been downloaded?',
    '下载次数不能为 0 哦': 'The number of downloads cannot be 0',
    '下载设置': 'Download Settings',
    '退出': 'Exit',
    '强制退出': 'Compulsory withdrawal',
    '下载数量': 'Download quantity',
    '下载模式选择': 'Download mode selection',
    'SSL证书启用': 'SSL certificate enable',
    '确认爬取': 'Confirm crawling',
    'result: 下载失败, 状态为: ': 'result: Download failed with status:',
    'result: 请输入正确的URL !': 'result: Please enter the correct URL',
    'result: 网址访问失败': 'result: Website access failed',
    '图片请求失败 !': 'Image request failed!',
    '图片数据处理出错 !': 'Image data processing error!',
    '状态码为: ': 'The status code is:',
    '没有发现图片的网址 !': 'No URL found for the images',
    '语言': 'Language',
    '请求超时 !': 'request timeout!',
    '不给 URL 怎么下载 ?': 'How to download without providing a URL?',
    '     请输入一个 URL !     ': '          Please enter a URL !          ',
    '下载中, 请稍候...': 'Downloading, please wait...',
    '通过返回的 JSON 对象获取图片': 'Obtaining images through the returned JSON object',
    '视频请求失败 !': 'Video request failed !',
    '视频数据处理出错 !': 'Video data processing error !',
    '通过视频所在的网页获取': 'Obtain through the webpage where the videos are located',
    '不支持的文件格式 !': 'Unsupported file format !',
    '通过视频自身的网址获取': 'Obtain them through the website of the videos themselves',
    '没有发现视频的网址 !': 'No video URL found !'
}

SimplifiedChinese_SimplifiedChinese = {
    '暂无': '暂无',
    '开启': '开启',
    '关闭': '关闭',
    '选择': '选择',
    '是否启用SSL证书验证 ?\n': '是否启用SSL证书验证 ?\n',
    '现在的状态为: ': '现在的状态为: ',
    '唔...要不还是都爬吧': '唔...要不还是都爬吧',
    '   请设置下载模式 !   ': '   请设置下载模式 !   ',
    '下...下载负数张图片!?': '下...下载负数张图片!?',
    '   不能填负数哦 !   ': '   不能填负数哦 !   ',
    '你是认真的吗 ?': '你是认真的吗?',
    '  请输入数字 !  ': '  请输入数字 !  ',
    '请输入下载的数量': '请输入下载的数量',
    '目前设置的下载数量为: ': '目前设置的下载数量为: ',
    '确定': '确定',
    '欸嘿, 还是我技高一筹 !': '欸嘿, 还是我技高一筹 !',
    '只能打开一个窗口哦 !': '只能打开一个窗口哦 !',
    '关于': '关于',
    '请选择下载的模式': '请选择下载的模式',
    '通过图片所在的网页获取': '通过图片所在的网页获取',
    '通过图片自身的网址获取': '通过图片自身的网址获取',
    '目前的下载设置为: ': '目前的下载设置为: ',
    '惊不惊喜, 意不意外 ?': '惊不惊喜, 意不意外 ?',
    '帮助': '帮助',
    '请先进行下载数量, 下载模式的设置。\n如果出错了, 可以先切换下载模式, 再尝试。\n注意:\n设置语言选项会使程序退出, 再启动程序, 更改便会生效。': '请先进行下载数量, 下载模式的设置。\n如果出错了, 可以先切换下载模式, 再尝试。\n注意:\n设置语言选项会使程序退出, 再启动程序, 更改便会生效。',
    '下载报告': '下载报告',
    '成功: ': '成功: ',
    '失败: ': '失败: ',
    '嗯? 没有下载吗 ?': '嗯? 没有下载吗 ?',
    '下载次数不能为 0 哦': '下载次数不能为 0 哦',
    '下载设置': '下载设置',
    '退出': '退出',
    '强制退出': '强制退出',
    '下载数量': '下载数量',
    '下载模式选择': '下载模式选择',
    'SSL证书启用': 'SSL证书启用',
    '确认爬取': '确认爬取',
    'result: 下载失败, 状态为: ': 'result: 下载失败, 状态为: ',
    'result: 请输入正确的URL !': 'result: 请输入正确的URL',
    'result: 网址访问失败': 'result: 网址访问失败',
    '图片请求失败 !': '图片请求失败 !',
    '图片数据处理出错 !': '图片数据处理出错 !',
    '状态码为: ': '状态码为: ',
    '没有发现图片的网址 !': '没有发现图片的网址 !',
    '语言': '语言',
    '请求超时 !': '请求超时 !',
    '不给 URL 怎么下载 ?': '不给 URL 怎么下载 ?',
    '     请输入一个 URL !     ': '     请输入一个 URL !     ',
    '下载中, 请稍候...': '下载中, 请稍候...',
    '通过返回的 JSON 对象获取图片': '通过返回的 JSON 对象获取图片',
    '视频请求失败 !': '视频请求失败 !',
    '视频数据处理出错 !': '视频数据处理出错 !',
    '通过视频所在的网页获取': '通过视频所在的网页获取',
    '不支持的文件格式 !': '不支持的文件格式 !',
    '通过视频自身的网址获取': '通过视频自身的网址获取',
    '没有发现视频的网址 !': '没有发现视频的网址 !'
}
